### PR TITLE
fix: current panel is null

### LINKED ISSUE #180: current panel can be null after calling setStauts
## Description
`getCurrentPanel` can return null after calling `setStatus`, even though there's panel exists.
스크린샷 2019-04-26 오전 10 56 09

## Steps to check or reproduce
1. Initiate flicking without any panel.
2. Add panel at index 2, by calling `replace(2, panel)`
3. call `setStatus()` with `getStatus()`'s return value

### PR DESCRIPTION
**Pull request by WoodNeck**
## Issue
#180 

## Details
- This fixes #180

### CODE REVIEW

File: src/components/Viewport.ts [hunk 1]
```diff
@@ -483,13 +484,18 @@ export default class Viewport {
...
 
     this.createPanels();
-    this.currentPanel = panelManager.get(status.index);
 
     // Reset panel index
     panelManager.originalPanels().forEach((panel, idx) => {
       panel.setIndex(panels[idx].index);
     });
 
+    this.currentPanel = panelManager.has(status.index)
```
Comment (daybrush) [inline src/components/Viewport.ts]: @WoodNeck 
How about `panelManager.get(status.index) || panelManager.get(defaultIndex) || panelManger.firstPanel()`?

Comment (WoodNeck) [reply src/components/Viewport.ts]: That looks more great, I'll fix it.
