### PR TITLE
fix: every panel to be initialized with CSS "left"

### LINKED ISSUE #213: CSS "left" value of first panel is not set when initialized
## Description
First panel's CSS `left` not exists after initialized. Not even `0px` is set.

## Cause
As Panel's default position is 0, and as Panel won't update position value if it's same value as currently holding, first panel's `left` won't be set.

### PR DESCRIPTION
**Pull request by WoodNeck**
## Issue
#213

## Details
This fixes #213

### CODE REVIEW

File: src/components/Viewport.ts [hunk 1]
```diff
@@ -710,7 +710,7 @@ export default class Viewport {
   }
 
   public setCurrentPanel(panel: Panel): void {
-    this.currentPanel = panel;
+    this.currentPanel = panel.getOriginalPanel();
```
Comment (jongmoon) [inline src/components/Viewport.ts]: @WoodNeck What is the purpose of this code? Doesn't it trigger more move?

Comment (WoodNeck) [reply src/components/Viewport.ts]: That's my mistake.
Looks like codes from other commit not omitted and included on this one.
