### PR TITLE
fix: touchmove not triggered when renderOnlyVisible option is enabled

### LINKED ISSUE #342: Using renderOnlyVisible option make panning stop
## Description
This happens only on mobile devices with touch events enabled.
As the `touchmove` / `touchend` event can be triggered when `touchstart` event's target element is not removed, renderOnlyVisible can make Flicking to stop.

## Steps to check or reproduce
1. Create Flicking instance with renderOnlyVisible option
2. Touch on one panel, and pan to make it disappear on the screen.

### PR DESCRIPTION
**Pull request by WoodNeck**
## Issue
#342

## Details
This fixes #342

### CODE REVIEW

File: src/components/Panel.ts [hunk 1]
```diff
@@ -434,7 +434,7 @@ class Panel implements FlickingPanel {
   public removeElement(): void {
     if (!this.viewport.options.renderExternal) {
       const element = this.element;
-      element.parentNode!.removeChild(element);
+      element.parentNode && element.parentNode.removeChild(element);
```
Comment (mixed) [inline src/components/Panel.ts]: The old code also looks good, why did it change? :)

File: src/components/Viewport.ts [hunk 2]
```diff
@@ -1770,68 +1783,67 @@ export default class Viewport {
...
+      // Visible panels not changed
+      return;
+    }
 
-      if (newVisiblePanels.length > 0) {
-        const firstVisiblePanelPos = newVisiblePanels[0].getPosition();
-        state.positionOffset = firstVisiblePanelPos;
-      }
+    if (currentState.holding) {
+      newVisiblePanels.push(...removedPanels);
```
Comment (mixed) [inline src/components/Viewport.ts]: WOW. I learned expression. Thanks.

File: src/components/Viewport.ts [hunk 3]
```diff
@@ -709,12 +724,58 @@ export default class Viewport {
...
+        }
+        return visiblePanels;
+      };
+
+      const panelCount = this.panelManager.getPanelCount();
+      const getAbsIndex = (panel: Panel) => panel.getIndex() + (panel.getCloneIndex() + 1) * panelCount;
+      const nextPanels = getVisiblePanels(basePanel, getNextPanel, isOutOfBoundNext);
+      const prevPanels = getVisiblePanels(basePanel, getPrevPanel, isOutOfBoundPrev);
+
+      return [basePanel, ...nextPanels, ...prevPanels].sort((panel1, panel2) => getAbsIndex(panel1) - getAbsIndex(panel2));
```
Comment (daybrush) [inline src/components/Viewport.ts]: @WoodNeck 

I've been thinking about this code and it looks like the code below is not a condition?
```js
return allPanels.filter(panel => {
        const outsetProgress = panel.getOutsetProgress();
        return outsetProgress > -1 && outsetProgress < 1;
      });
```

File: src/components/Viewport.ts [hunk 4]
```diff
@@ -1894,9 +1906,9 @@ export default class Viewport {
     };
 
     // Stopped on first cloned first panel
-    if (lastPanelOfPrevDir.getIndex() === 0 && lastPanelOfPrevDir.getCloneIndex() === 0) {
-      newVisibleIndex.min = allPanelCount;
-    }
+    // if (lastPanelOfPrevDir.getIndex() === 0 && lastPanelOfPrevDir.getCloneIndex() === 0) {
```
Comment (daybrush) [inline src/components/Viewport.ts]: @WoodNeck

Is this code now unnecessary?

File: src/components/Viewport.ts (hunk 3 above)
Comment (WoodNeck) [reply src/components/Viewport.ts]: You're right. That should work for the non-renderOnlyVisible cases.
I'll see that works.

File: src/components/Viewport.ts (hunk 4 above)
Comment (WoodNeck) [reply src/components/Viewport.ts]: Yes not they're unnecessary. I've just forgot to remove them.

File: src/components/Panel.ts (hunk 1 above)
Comment (WoodNeck) [reply src/components/Panel.ts]: There can be a case that elements can be removed without parentNode.
It's when `remove()` is called by that removed panel is part of visible panels so that it could be removed twice. That code prevents such case.

File: src/components/Viewport.ts (hunk 3 above)
Comment (WoodNeck) [reply src/components/Viewport.ts]: I figured why. That's basically more efficient to do that.
Filtering all panels can be unnecessary when cases like there're plenty of panels but only 3 panels are visible.
