### PR TITLE
fix: clone count calculation

### LINKED ISSUE #241: Clone count is miscalculated
## Description
Flicking's clone count is miscalculated in circular mode.

## Steps to check or reproduce
https://codepen.io/woodneck/pen/jjNmaG

### LINKED ISSUE #243: Resize makes more clones
## Description
`resize()` makes more cloned panels at initialization.

## Steps to check or reproduce
Call flicking's resize() method at initialization.

### PR DESCRIPTION
**Pull request by WoodNeck**
## Issue
#241, #243 

## Details
This fixes #241
It also fixes #243

### CODE REVIEW

File: src/components/Viewport.ts [hunk 1]
```diff
@@ -953,26 +953,67 @@ export default class Viewport {
...
+      sizeSum += panel.getSize() + gap;
+      if (sizeSum >= areaNext) {
+        panelAtRightBoundary = panel;
+        break;
+      }
+    }
+
+    // Need one more set of clones on prev area of original panel 0
+    const needCloneOnPrev = panelAtLeftBoundary.getIndex() <= panelAtRightBoundary.getIndex()
+      && panelAtLeftBoundary.getIndex() !== 0;
```
Comment (jongmoon) [inline src/components/Viewport.ts]: @WoodNeck Although it's not important and not critical. But it would be better to check `panelAtLeftBoundary.getIndex() !== 0` first and `panelAtLeftBoundary.getIndex() <= panelAtRightBoundary.getIndex()` later. 

Because
  1. if **0 check** is failed, it doesn't need to access getIndex of Right boundary.
  2. it would be more readable if more simple condition precedes.

File: src/components/Viewport.ts [hunk 2]
```diff
@@ -953,26 +953,67 @@ export default class Viewport {
...
+
+    // Visible count of panel 0 on first screen
+    const panel0OnFirstscreen = Math.ceil((relativeHangerPosition + firstPanel.getSize() - relativeAnchorPosition) / sumOriginalPanelSize)
+      + Math.ceil((viewportSize - relativeHangerPosition + relativeAnchorPosition) / sumOriginalPanelSize)
+      - 1;
```
Comment (jongmoon) [inline src/components/Viewport.ts]: Is last `-1` calc for considering intersection of A and B?
  - A: `Math.ceil((relativeHangerPosition + firstPanel.getSize() - relativeAnchorPosition) / sumOriginalPanelSize)`
  - B: `Math.ceil((viewportSize - relativeHangerPosition + relativeAnchorPosition) / sumOriginalPanelSize)`

Comment (WoodNeck) [reply src/components/Viewport.ts]: That's right

File: src/components/Viewport.ts (hunk 1 above)
Comment (WoodNeck) [reply src/components/Viewport.ts]: That looks good, I'll fix that.
