### PR TITLE
fix: recalculate target panel when interrupted

### LINKED ISSUE #171: Target panel isn't recalculated if interrupted in circular mode
## Description
Version: Flicking 3.0.0

b11f1e10-40fd-11e9-8535-aa61c3fec8b5

## Steps to check or reproduce
1. Circular.
2. Animating to further than first cloned panel.
3. Interrrupted while moving.
Then, target panel isn't recalculated, so it will move further than expected.

### LINKED ISSUE #174: snap option is not from release position, but start position
## Description
`snap` option is applied from `currentPanel`, but should be applied on `nearestPanel`.

## Steps to check or reproduce
Test any flicking instance with `snap` option applied.
Drag more then one panel, then release with speed to test snap.

### PR DESCRIPTION
**Pull request by WoodNeck**
## Issue
Fixes #171 
It also resolves #174 

## Details
- This changes internal interface from FlickingPanel to real Panel's instance
- #171 is now fixed.
- #174 is also handled on this PR.

### CODE REVIEW

File: src/components/Panel.ts [hunk 1]
```diff
@@ -74,6 +78,163 @@ class Panel {
...
+
+    const newPosition = currentPosition - prevPanelSize - options.gap;
+
+    let prevPanel = prevSibling;
+    if (prevPanelPosition >= currentPosition) {
+      prevPanel = prevSibling.clone(prevSibling.getCloneIndex(), true);
+      prevPanel.setPosition(newPosition, true);
+    }
+
+    return prevPanel;
```
Comment (daybrush) [inline src/components/Panel.ts]: @WoodNeck 
It's a special case.
In circular mode, if enough virtual clones are created through prev() calls, then next(), the clones are not created.

File: src/components/Panel.ts [hunk 2]
```diff
@@ -74,6 +78,163 @@ class Panel {
...
+    }
+
+    const newPosition = currentPosition + this.getSize() + options.gap;
+
+    let nextPanel = nextSibling;
+    if (nextPanelPosition <= currentPosition) {
+      nextPanel = nextSibling.clone(nextSibling.getCloneIndex(), true);
+      nextPanel.setPosition(newPosition, true);
+    }
+
```
Comment (daybrush) [inline src/components/Panel.ts]: @WoodNeck 
The same is true if the opposite is done, as in the above comments.

File: src/components/Panel.ts (hunk 1 above)
Comment (WoodNeck) [reply src/components/Panel.ts]: Okay, I forgot to consider that one. I'll push fixing commit for it.

Comment (WoodNeck) [reply src/components/Panel.ts]: I couldn't reproduce condition you mentioned. Can you give me some more details?

Comment (WoodNeck) [reply src/components/Panel.ts]: Okay, now I got what's the problem.
I'll push fixing commit for it.

File: src/states/AnimatingState.ts [hunk 3]
```diff
@@ -1,20 +1,38 @@
...
+    const scrollAreaSize = viewport.getScrollAreaSize();
+    const loopCount = Math.floor((this.lastPosition + this.delta - scrollArea.prev) / scrollAreaSize);
+
+    let targetPanel = this.targetPanel;
+    if (loopCount !== 0 && targetPanel) {
+      const cloneCount = viewport.panelManager.getCloneCount();
+      const originalTargetPosition = targetPanel.getPosition();
+
+      // cloneIndex is from -1 to cloneCount - 1
+      const newCloneIndex = circulate(targetPanel.getCloneIndex() - loopCount, -1, cloneCount - 1);
```
Comment (daybrush) [inline src/states/AnimatingState.ts]: @WoodNeck 
Is there a chance that newCloneIndex will get -1?

Comment (WoodNeck) [reply src/states/AnimatingState.ts]: As written in comment, cloneIndex is from -1 to cloneCount - 1
It's because original panel's cloneIndex is -1, and clone's cloneIndex starts from 0.
I've wrote code in that way as it's more convenient to manage clones like that.

So, newCloneIndex can be -1, if virtual panel is pointing original panel.

File: src/components/Panel.ts [hunk 4]
```diff
@@ -74,6 +80,170 @@ class Panel {
...
+    if (hangerPosition === anchorPosition || !currentPanel) {
+      return;
+    }
+
+    const currentPosition = currentPanel.getPosition();
+    const eventType = currentPosition === this.getPosition()
+      ? ""
+      : EVENTS.CHANGE;
+
+    console.log(duration);
```
Comment (jongmoon) [inline src/components/Panel.ts]: log remained.

Comment (WoodNeck) [reply src/components/Panel.ts]: That file's outdated, and fixed on later commit.
