### PR TITLE
fix: react - prevent update between rendering

### LINKED ISSUE #736: Flicking._panels array is unmatched to Flicking.panels array in react-flicking
## Description
react-flicking 사용중 아래와 같은 에러가 발생합니다.

```
flicking.esm.js:5335 

Uncaught TypeError: Cannot read properties of null (reading '_reactInternals')
    at flicking.esm.js:5335:1
    at Array.map (<anonymous>)
    at flicking.esm.js:5335:1
    at Array.reduce (<anonymous>)
    at __proto.batchInsertDefer (flicking.esm.js:5310:1)
    at batchInsert (flicking.esm.js:8875:1)
    at sync (flicking.esm.js:8865:1)
    at __proto.componentDidUpdate (flicking.esm.js:596:9)
    at commitLayoutEffectOnFiber (react-dom.development.js:23333:1)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:1)
```

디버깅 좀 해보니, `_panels`배열과 `panels`배열이 다르게 나온다는걸 알게되었고, 이 부분이 문제의 근원이라고 추측됩니다.
(`_panels`는 최신 상태가 잘 반영되었고, `panels`는 반영이 안된 것으로 보입니다.)

좀 더 자세히 말하면,
`getRenderingPanels`에서 , `diffResult`를 기반으로 새로운 children을 생성할 때 (`diffResult`는 제대로 나옵니다),
`flicking.panels`배열을 기반으로 생성하는데, 이 `flicking.panels`배열이 최신화가 안된 상태라 엉뚱한 children이 나옵니다.

recoil과 함께 사용중인데, 혹시 recoil과의 이슈가 있는지도 확인해주시면 감사하겠습니다.

## Steps to check or reproduce
아래와 같이 래핑해서 사용하고 있고, 필드값이 다른건 아래 코드처럼 로그를 찍어서 확인해봤습니다..
```jsx
const Layout = ({
  children,
}) => {
  const flickingRef = useRef(null);

  console.log(flickingRef.current?._panels, flickingRef.current?.panels);

  return (
    <Flicking
      ref={flickingRef}
    >
      {children}
    </Flicking>
  );
};
```

코드베이스가 커서, 간추려서 재현해보려고했는데 재현이 안돼서 정보가 좀 부족할 수 있는데요..
혹시라도 위와 같은 문제가 발생하는 상황을 알고계신다면 알려주시면 감사하겠습니다 🙇🏻‍♂️

### PR DESCRIPTION
**Pull request by WoodNeck**
## Issue
#736 

## Details
This fixes #736 

Tested this doesn't produce any error furthermore on both this two test cases:
- https://github.com/neizzz/flicking-bug-reproduction
- https://codesandbox.io/s/flicking-change-data-bug-voblvn

### CODE REVIEW

**Review by malangfox — APPROVED** [review]
LGTM, Confirmed this fix works correctly for reported error cases.
It is not related with this PR but while checking this issue, I noticed that console.log was included in the `_hasSameChildren` fron recent PR.
Looks like that part should be removed before release.

**Comment by WoodNeck** [comment]
> LGTM, Confirmed this fix works correctly for reported error cases. It is not related with this PR but while checking this issue, I noticed that console.log was included in the `_hasSameChildren` fron recent PR. Looks like that part should be removed before release.

Good point, I'll include that in this PR

File: packages/react-flicking/src/react-flicking/Flicking.tsx [hunk 1]
```diff
@@ -138,6 +152,7 @@ class Flicking extends React.Component<Partial<FlickingProps & FlickingOptions>>
 
     sync(flicking, diffResult, this.reactPanels);
 
+    this._renderingState = RenderingState.UPDATED;
```
Comment (daybrush) [inline packages/react-flicking/src/react-flicking/Flicking.tsx:155]: If it is the same children even once, the renderingState is likely to be RENDERED forever.

Comment (WoodNeck) [reply packages/react-flicking/src/react-flicking/Flicking.tsx:155]: Good point.

File: packages/react-flicking/src/react-flicking/Flicking.tsx [hunk 2]
```diff
@@ -133,6 +147,7 @@ class Flicking extends React.Component<Partial<FlickingProps & FlickingOptions>>
     this._checkPlugins();
     renderEmitter.trigger("render");
     flicking.camera.updateOffset();
+    this._renderingState = RenderingState.UPDATED;
```
Comment (daybrush) [inline packages/react-flicking/src/react-flicking/Flicking.tsx:150]: If it is used like this, does renderingState seem to have no meaning?

Comment (WoodNeck) [reply packages/react-flicking/src/react-flicking/Flicking.tsx:150]: It's meant to prevent updates in `beforeRender` when there're two render calls without calling  `componentDidUpdate`.

Comment (daybrush) [reply packages/react-flicking/src/react-flicking/Flicking.tsx:150]: Have you checked codesandbox with the fixed code?

Comment (WoodNeck) [reply packages/react-flicking/src/react-flicking/Flicking.tsx:150]: > ## Issue
> #736
> 
> ## Details
> This fixes #736
> 
> Tested this doesn't produce any error furthermore on both this two test cases:
> 
> * https://github.com/neizzz/flicking-bug-reproduction
> * https://codesandbox.io/s/flicking-change-data-bug-voblvn

Yes.

But, the commit you suggested https://github.com/naver/egjs-flicking/pull/739/commits/852d63f76d65e32f723212dc8e0eb59bad902f8e actually broke that case.
I found the reason & I'll revert that with more explanation of it.

**Review by daybrush — APPROVED** [review]
LGTM
