### PR TITLE
fix: current panel can be cloned one

### LINKED ISSUE #250: Calling next() on first clone of panel 0 will move to previous panel in circular mode
## Description
If `next()` is called on first cloned panel 0, it will move to prev direction.

## Steps to check or reproduce
1. Init Flicking with `circular: true;`
2. Move to first cloned panel 0
3. Call `next()`

### PR DESCRIPTION
**Pull request by WoodNeck**
## Issue
#250 

## Details
This fixes #250

### CODE REVIEW

File: src/components/Viewport.ts [hunk 1]
```diff
@@ -727,7 +727,7 @@ export default class Viewport {
   }
 
   public setCurrentPanel(panel: Panel): void {
-    this.currentPanel = panel.getOriginalPanel();
+    this.currentPanel = panel;
```
Comment (jongmoon) [inline src/components/Viewport.ts]: is #247 no more needed?

Comment (WoodNeck) [reply src/components/Viewport.ts]: #247 still can be useful while in animating, but it's not that important at the moment.
