### PR TITLE
fix: change event is triggered on bound area

### LINKED ISSUE #208: change event is triggered at bound area
## Description
`change` event is triggered at bound area when Flicking is initialized with option
`bounce: 0, bound: true, moveType: freeScroll`

## Steps to check or reproduce
1. Initialize Flicking with above options.
2. Scroll to bound area

### PR DESCRIPTION
**Pull request by WoodNeck**
## Issue
#208

## Details
This fixes #208

### CODE REVIEW

File: src/moves/FreeScroll.ts [hunk 1]
```diff
@@ -65,13 +89,13 @@ class FreeScroll extends Snap {
     // Ref #191(https://github.com/naver/egjs-flicking/issues/191)
     const lastHangerPosition = lastPosition + viewport.getRelativeHangerPosition();
 
+    const scrollAreaSize = viewport.getScrollAreaSize();
     let minimumDistanceToChange = isNextDirection
       ? currentPanelPosition + currentPanel.getSize() - lastHangerPosition + halfGap
       : lastHangerPosition - currentPanelPosition + halfGap;
+    minimumDistanceToChange = Math.abs(minimumDistanceToChange % scrollAreaSize);
```
Comment (daybrush) [inline src/moves/FreeScroll.ts]: @WoodNeck Why did you get the rest of it?

Comment (WoodNeck) [reply src/moves/FreeScroll.ts]: In scroll boundary area in circular mode, `minimumDistanceToChange` can be calculated from cloned panel 0 to original panel 0 or vice versa.
In that case, distance from original panel 0 to cloned panel 0 is added to `minimumDistanceToChange` and `scrollAreaSize` is it.
So by taking modulus, we can calculate correct `minimumDistanceToChange`
