### PR TITLE
fix: renderOnlyVisible not correctly positioning panels on the first render

### LINKED ISSUE #382: Panels are not positioned correctly with renderOnlyVisible option
## Description
Panels are not positioned correctly with renderOnlyVisible option when if all panels can be shown on the full viewport.

## Steps to check or reproduce
1. Enable "renderOnlyVisible" option
2. Place panels to not exceed viewport size, make sure any of the panels are hidden.

### PR DESCRIPTION
**Pull request by WoodNeck**
## Issue
#382

## Details
This fixes #382

### CODE REVIEW

File: src/components/Viewport.ts [hunk 1]
```diff
@@ -1086,6 +1086,10 @@ export default class Viewport {
     this.setDefaultPanel();
     this.resize();
     this.moveToDefaultPanel();
+    if (this.options.renderOnlyVisible) {
```
Comment (daybrush) [inline src/components/Viewport.ts:1089]: @WoodNeck 
this part is only for the first rendering.  I know that css is not injected even if resized.

**Review by mixed — APPROVED** [review]

**Review by daybrush — APPROVED** [review]
LGTM
