### PR TITLE
fix: resize() binding for window resize event

### LINKED ISSUE #248: Enabling autoResize option triggers error
## Description
Enabling Flicking's `autoResize` option triggers error.

image

## Steps to check or reproduce
Init Flicking with `autoResize` option, then change window size.

### PR DESCRIPTION
**Pull request by WoodNeck**
## Issue
#248

## Details
This fixes #248

### CODE REVIEW

File: src/Flicking.ts [hunk 1]
```diff
@@ -447,7 +447,7 @@ class Flicking extends Component {
    * @ko 패널들을 현재 상태에 맞춰 갱신한다.
    * @return {eg.Flicking} The instance itself.<ko>인스턴스 자기 자신.</ko>
    */
-  public resize(): this {
+  public resize = (): this => {
```
Comment (jongmoon) [inline src/Flicking.ts]: @WoodNeck @daybrush Is it more preferable than `bind(this)`?

Comment (WoodNeck) [reply src/Flicking.ts]: I think it's more simple.
