### PR TITLE
fix: text node can be used as panel

### LINKED ISSUE #327: Vue - element.getAttribute is not a function
## Description
image
```
[Vue warn]: Error in directive children-differ componentUpdated hook: "TypeError: element.getAttribute is not a function"

found in

---> <Flicking>
       <KeywordScore> at src/components/KeywordScore.vue
         <App> at src/App.vue
           <Root>

vue.esm.js?efeb:1897 TypeError: element.getAttribute is not a function
    at Panel.__proto.setElement (flicking.esm.js?1454:902)
    at eval (flicking.esm.js?1454:4917)
    at Array.forEach (<anonymous>)
    at Flicking.__proto.sync (flicking.esm.js?1454:4914)
    at VueComponent.__proto.onUpdate (flicking.esm.js?bcd9:184)
    at componentUpdated (children-differ.esm.js?2cdd:25)
    at callHook$1 (vue.esm.js?efeb:6685)
    at eval (vue.esm.js?efeb:6637)
    at wrappedHook (vue.esm.js?efeb:2244)
    at invokeWithErrorHandling (vue.esm.js?efeb:1863)
```

This can happen when the text node is used for the Flicking panel.

### PR DESCRIPTION
**Pull request by WoodNeck**
## Issue
#327

## Details
This fixes #327

### CODE REVIEW

File: packages/vue-flicking/demo/plugins/Autoplay.vue [hunk 1]
```diff
@@ -37,7 +37,11 @@ export default class AutoPlayDemo extends Vue {
   }
 
   plugins = [new Fade(), new AutoPlay(2000, "NEXT")];
-  code0 = `<flicking
+  code0 = `<!--
+  import { Fade, AutoPlay } from "@egjs/flicking-plugins";
+  plugins = [new Fade(), new AutoPlay(2000, "NEXT")];
```
Comment (daybrush) [inline packages/vue-flicking/demo/plugins/Autoplay.vue]: @WoodNeck

It seems'd better add a `const`.

File: packages/vue-flicking/src/Flicking.ts [hunk 2]
```diff
@@ -149,7 +146,7 @@ export default class Flicking extends Vue {
 
   private $_getPanels(h: CreateElement) {
     const flicking = this.$_nativeFlicking;
-    const wholeSlots = this.$slots.default;
+    const wholeSlots = this.$_getSlots();
 
     if (!wholeSlots) {
```
Comment (daybrush) [inline packages/vue-flicking/src/Flicking.ts]: @WoodNeck


It seems to be true because wholeSlots is always an array. How about using length in this case?

File: packages/vue-flicking/src/Flicking.ts [hunk 3]
```diff
@@ -149,7 +146,7 @@ export default class Flicking extends Vue {
 
   private $_getPanels(h: CreateElement) {
     const flicking = this.$_nativeFlicking;
-    const wholeSlots = this.$slots.default;
+    const wholeSlots = this.$_getSlots();
```
Comment (daybrush) [inline packages/vue-flicking/src/Flicking.ts]: @WoodNeck

It seems to be true because wholeSlots is always an array. How about using length in this case?

Comment (WoodNeck) [reply packages/vue-flicking/src/Flicking.ts]: Thanks for checking! I'll fix that.

File: packages/vue-flicking/demo/plugins/Autoplay.vue (hunk 1 above)
Comment (WoodNeck) [reply packages/vue-flicking/demo/plugins/Autoplay.vue]: I'll fix that!
