### PR TITLE
fix: prevent scrolling when resize

### LINKED ISSUE #333: Flicking can be scrolled to top when address bar in mobile browser appear/disappears.
## Description
When the address bar in the mobile browser appear or disappears, the `resize` event is triggered.
When Flicking has `autoResize` option, Flicking will attempt to calculate viewport size based on new panel size.
And in that sequence, Flicking will set viewport height to ""(none) to calculate viewport-dependent panel size correctly. (see #201)
As all panel has `position:absolute`, viewport's height will be once 0, so it will be scrolled to -y based on viewport's size.

## Steps to check or reproduce
1. Make Flicking with sufficient height(horizontal: true), and option `autoResize: true`
2. On the mobile device, scroll enough to make address bar disappear so resize event can be triggered.

### PR DESCRIPTION
**Pull request by WoodNeck**
## Issue
#333

## Details
This fixes #333

### CODE REVIEW

File: src/components/Viewport.ts [hunk 1]
```diff
@@ -597,8 +597,10 @@ export default class Viewport {
       const viewportSize = `${sizeToApply}px`;
       if (horizontal) {
         viewportStyle.height = viewportSize;
+        state.cachedBbox!.height = sizeToApply;
       } else if (!horizontal) {
```
Comment (daybrush) [inline src/components/Viewport.ts]: @WoodNeck 

Is it just else?

Comment (WoodNeck) [reply src/components/Viewport.ts]: That definitely is. My mistake.
